### ISSUE TITLE
Unresolved reference: ShoppingListItem

### ISSUE THREAD

**Issue by MattPappacena** [kotlin-hands-on/jvm-js-fullstack#15]
Hi,

I am having an issue similar to one posted here: [https://github.com/kotlin-hands-on/jvm-js-fullstack/issues/1](url) . While following the tutorial. I think that Server.kts does not recognize ShoppingListItem from src/commonMain/ShoppingListItem.kts

I read Sebastian's response in the above post, but I am new to Gradle and Kotlin and I don't think I followed his instruction properly. I tried to change the version in the build.gradle.kts plugin block from "1.6.10" to "1.3.72" but the build failed after making the change. 

I ran the project using the './gradlew run'' command from the command line.

Any help on to resolve this would be awesome! 

Images for error, build.gradle plugin block, and ShoppingListItem.kts: [https://imgur.com/a/gnifvMY](url)

**Comment by SebastianAigner** [comment]
Hi @MattPappacena! We're updating the tutorial in the upcoming days with some changes.

In the meantime, you can check if IntelliJ IDEA is properly showing the files to be resolved in your `Server.kt` file. If you're seeing any red code, a quick fix (via Alt-Enter) might be available to fix any missing imports. If that's not the case, I'm happy to take a closer look.

**Comment by MattPappacena** [comment]
Thank you for your response! I have been using VSCode and WSL2, but I will try re-doing the tutorial with InelliJ IDEA and see if that fixes the issue and will report back.

**Comment by boosh** [comment]
Ah I've just upgraded to Inteillij 2022.3 and it seems to work now.

**Comment by SebastianAigner** [comment]
Thanks for the feedback, @boosh ! I'm gonna close this issue for now, seeing how it seems to work with the latest IntelliJ versions. If there's another problem that reappears, please give me a shout / open a new issue, and I'll take a look. Thanks!
