### ISSUE TITLE
Script isn't loading

### ISSUE THREAD

**Issue by sangeetds** [kotlin-hands-on/jvm-js-fullstack#3]
Hi. 
I cloned the final branch and was running on my pc. It compiled and ran without issues but when it loaded on my browser, it wasn't displaying the script. I went and checked my index.html and made some changes like adding a header. These changes I could properly see on the browser but I guess the browser couldn't load the script. 
What I did was to just clone the final branch and run the server and open the localhost url on my browser. Is there anything else I am missing or something else that needs to be done?

**Comment by SebastianAigner** [comment]
Hi @sangeetds ! I've just tried to reproduce your issue, but I didn't encounter the same problems as you.
What I did:
- check out the `https://github.com/kotlin-hands-on/jvm-js-fullstack/` repository
- switch to the `final` branch
- Run the Gradle `run` task

This successfully compiled and delivered everything on my machine (where I also have a MongoDB instance running).

If you started the application differently – for example with "play button" gutter icon in IntelliJ IDEA, it could be that you are not running the whole application, but only the server. Please try running the application again using the Gradle `run` task. IF that doesn't work, feel free to let me know.

![image](https://user-images.githubusercontent.com/2178959/91715105-59ef6a00-eb8d-11ea-8f0f-cddaee2beb09.png)

**Comment by sangeetds** [comment]
Hi. Thanks for the reply! Ya, I was following the guide only and I thought the run option there meant running through the play button. Running through gradle works. Thanks for clearing this silly doubt.
