### ISSUE TITLE
Error while analyzing code

### ISSUE THREAD

**Issue by ReyMagos** [kotlin-hands-on/jvm-js-fullstack#4]
When I clone the final-branch the following error was found in App.kt (https://pastebin.com/MgULxL3R)
Idea sayd to me, that I must report this error and I did it! I'll be happy to solve this problem. Thank you!

While executing gradle task "run" I have another error:
Caused by: java.io.IOException: ��������� ��������� �������� ��� ������� �����������.

**Comment by SebastianAigner** [comment]
Hey! We’ve overhauled the code for this tutorial. If any problems remain, please do not hesitate to file another issue.
