### ISSUE TITLE
Error building initial version of project

### ISSUE THREAD

**Issue by mlidal** [kotlin-hands-on/jvm-js-fullstack#6]
Hello.

I've just cloned this project to try out the kotlin multiplatform full-stack tutorial.
However, during the initial load of the project (in Intellij IDEA Ultimate), the build fails with the following error:
Unexpected exception while resolving Gradle distribution sources: Could not resolve all files for configuration ':detachedConfiguration28'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find gradle-12.16.1-src.zip (org.nodejs:node:12.16.1).
Searched in the following locations:
    https://services.gradle.org/distributions/node-12.16.1-src.zip

Trying to access the above mentioned url results in the following error:
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>distributions/node-12.16.1-src.zip</Key>
<RequestId>ZMP4FBTJWJ03MZQH</RequestId>
<HostId>
FhnGWozmKGPHSwet6yRq9f40VORydNynLy82sjFG19aHj8qzzYWwBowGI/bLQ8KZ0IF5dI/aOpA=
</HostId>
</Error>

Update: I see now that the project still seems to run, despite this error. However, it still looks quite bad for a beginner :)

**Comment by SebastianAigner** [comment]
Hi @mlidal!
Unfortunately, I can't reproduce this issue on my machine.
Could I ask you to do another clean checkout of the project, and run `./gradlew run` from the command line? That should print `Hello, JVM!`. Maybe we can narrow down the problem like this.

**Comment by SebastianAigner** [comment]
Hey! We’ve overhauled the code for this tutorial. If any problems remain, please do not hesitate to file another issue.
