### ISSUE TITLE
Infinite loop calling GET endpoint

### ISSUE THREAD

**Issue by jeffdgr8** [kotlin-hands-on/jvm-js-fullstack#9]
This code:

```
useEffect {
    scope.launch {
        setShoppingList(getShoppingList())
    }
}
```

causes an infinite loop, repeatedly calling the GET endpoint and updating the state, triggering the update over and over again.

Using [`useEffectOnce`](https://github.com/JetBrains/kotlin-wrappers/blob/master/kotlin-react/README.md#the-useeffect-hook) instead will resolve this.

```
useEffectOnce {
    scope.launch {
        setShoppingList(getShoppingList())
    }
}
```

**Comment by SebastianAigner** [comment]
Thanks so much! We’ve completely overhauled this tutorial to be compatible with the latest version of the wrappers, which also fixes this! I appreciate y’all pointing it out.
